// Generated by CoffeeScript 1.8.0
(function() {
  window.ExportTrelloApp = angular.module('ExportTrelloApp', ['ngRoute', 'ngCookies', 'ui.bootstrap']);

  ExportTrelloApp.config([
    '$interpolateProvider', function($interpolateProvider) {
      return $interpolateProvider.startSymbol('{(').endSymbol(')}');
    }
  ]).config([
    '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
      return $routeProvider.when('/dashboard', {
        templateUrl: 'partials/dashboard.html',
        controller: 'MainController'
      }).when('/boards', {
        templateUrl: 'partials/boards.html',
        controller: 'BoardsController'
      }).when('/lists/', {
        templateUrl: 'partials/lists.html',
        controller: 'ListsController'
      }).otherwise({
        redirectTo: '/dashboard'
      });
    }
  ]).factory('TrelloService', [
    '$http', '$cookieStore', function($http, $cookieStore) {
      var TrelloService;
      return TrelloService = (function() {
        var APIENDPOINT;

        function TrelloService() {}

        APIENDPOINT = "https://api.trello.com/1/";

        TrelloService.token = function() {
          return $cookieStore.get("trelloToken");
        };

        TrelloService.setToken = function() {
          return $cookieStore.put("trelloToken", Trello.token());
        };

        TrelloService.user = function() {
          return $cookieStore.get("trelloUser");
        };

        TrelloService.setUser = function(username) {
          return $cookieStore.put('trelloUser', username);
        };

        TrelloService.boards = function() {
          return $http.get(APIENDPOINT + ("members/" + (this.user()) + "/boards?key=9115435cc98b67a65c3a6dcff606cb09&token=" + (this.token()) + "&filter=open"));
        };

        TrelloService.lists = function(boardId) {
          return $http.get(APIENDPOINT + ("boards/" + boardId + "/lists?key=9115435cc98b67a65c3a6dcff606cb09&token=" + (this.token())));
        };

        TrelloService.cards = function(listId) {
          return $http.get(APIENDPOINT + ("lists/" + listId + "/cards?key=9115435cc98b67a65c3a6dcff606cb09&token=" + (this.token()) + "&filter=open"));
        };

        return TrelloService;

      })();
    }
  ]).controller('MainController', [
    '$scope', '$http', '$location', '$rootScope', 'TrelloService', function($scope, $http, $location, $rootScope, TrelloService) {
      $scope.TrelloService = TrelloService;
      $scope.organizationName = "bstar";
      window.TrelloService = TrelloService;
      $scope.authorized = function() {
        return Trello.authorized();
      };
      $scope.authorize = function() {
        return Trello.authorize({
          type: "popup",
          success: function() {}
        });
      };
      $scope.deauthorize = function() {
        return Trello.deauthorize();
      };
      $scope.getDatas = function() {
        return TrelloService.getDatas($scope.organizationName);
      };
      return $scope.lists = function(id) {
        return $location.path('/lists').search({
          boardId: id
        });
      };
    }
  ]).controller('BoardsController', [
    '$scope', '$location', '$http', '$rootScope', 'TrelloService', function($scope, $location, $http, $rootScope, TrelloService) {
      $scope.boards = [];
      $scope.index = function() {
        return TrelloService.boards().then(function(response) {
          return $scope.boards = response.data;
        });
      };
      $scope.lists = function(id) {
        return $location.path('lists').search({
          boardId: id
        });
      };
      return $scope.index();
    }
  ]).controller('ListsController', [
    '$scope', '$location', '$http', '$rootScope', 'TrelloService', function($scope, $location, $http, $rootScope, TrelloService) {
      $scope.board = null;
      $scope.selectedListId = null;
      $scope.cards = null;
      $scope.drawPaper = function() {
        var card, content, project, projectKeyTitle, projects, _i, _len, _ref, _results;
        projects = {};
        _ref = $scope.cards;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          card = _ref[_i];
          if (!card.name.match(/\{(.*)}/)) {
            break;
          }
          projectKeyTitle = card.name.match(/\{(.*)}/)[1];
          if (!projects[projectKeyTitle]) {
            projects[projectKeyTitle] = [];
          }
          projects[projectKeyTitle].push(card);
        }
        $("#paper").empty();
        _results = [];
        for (project in projects) {
          $("<h2 />", {
            text: project
          }).appendTo("#paper");
          _results.push((function() {
            var _j, _len1, _ref1, _results1;
            _ref1 = projects[project];
            _results1 = [];
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              card = _ref1[_j];
              content = card.name;
              _results1.push($("<div/>", {
                text: content
              }).appendTo("#paper"));
            }
            return _results1;
          })());
        }
        return _results;
      };
      $scope.index = function() {
        return TrelloService.lists($location.search().boardId).then(function(response) {
          $scope.lists = response.data;
          $scope.selectedListId || ($scope.selectedListId = $scope.lists[0].id);
          return $scope.show($scope.selectedListId);
        });
      };
      $scope.show = function(id) {
        $scope.selectedListId = id;
        return TrelloService.cards(id).then(function(response) {
          $scope.cards = response.data;
          return $scope.drawPaper();
        });
      };
      return $scope.index();
    }
  ]);

}).call(this);
