// Generated by CoffeeScript 1.8.0
(function() {
  window.ExportTrelloApp = angular.module('ExportTrelloApp', ['ngRoute', 'ui.bootstrap']);

  ExportTrelloApp.config([
    '$interpolateProvider', function($interpolateProvider) {
      return $interpolateProvider.startSymbol('{(').endSymbol(')}');
    }
  ]).config([
    '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
      return $routeProvider.when('/dashboard', {
        templateUrl: 'partials/dashboard.html',
        controller: 'MainController'
      }).otherwise({
        redirectTo: '/dashboard'
      });
    }
  ]).factory('TrelloService', [
    '$http', function($http) {
      var TrelloService;
      return TrelloService = (function() {
        function TrelloService() {}

        TrelloService.organizations = {};

        TrelloService.getDatas = function(organizationName) {
          if (this.organizations[organizationName] != null) {
            return;
          }
          return $http.get("https://api.trello.com/1/organizations/" + organizationName + "?boards=open&key=9115435cc98b67a65c3a6dcff606cb09&token=" + Trello.token()).success((function(_this) {
            return function(data, status, headers, config) {
              return _this.organizations[organizationName] = data;
            };
          })(this));
        };

        return TrelloService;

      })();
    }
  ]).controller('MainController', [
    '$scope', '$http', '$location', '$rootScope', 'TrelloService', function($scope, $http, $location, $rootScope, TrelloService) {
      $scope.TrelloService = TrelloService;
      $scope.organizationName = "bstar";
      $scope.authorized = function() {
        return Trello.authorized();
      };
      $scope.getDatas = function() {
        return TrelloService.getDatas($scope.organizationName);
      };
      $scope.authorize = function() {
        return Trello.authorize({
          type: "popup",
          success: function() {
            return TrelloService.getDatas($scope.organizationName);
          }
        });
      };
      return $scope.deauthorize = function() {
        return Trello.deauthorize();
      };
    }
  ]).controller('BoardsController', [
    '$scope', '$location', '$http', '$rootScope', 'TrelloService', function($scope, $location, $http, $rootScope, TrelloService) {
      return $scope.TrelloService = TrelloService;
    }
  ]);

}).call(this);
