// Generated by CoffeeScript 1.9.3
(function() {
  window.ExportTrelloApp = angular.module('ExportTrelloApp', ['ngRoute', 'ngCookies', 'ui.bootstrap']);

  ExportTrelloApp.config([
    '$interpolateProvider', function($interpolateProvider) {
      return $interpolateProvider.startSymbol('{(').endSymbol(')}');
    }
  ]).config([
    '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
      return $routeProvider.when('/login', {
        templateUrl: 'partials/login.html',
        controller: 'MainController'
      }).when('/boards', {
        templateUrl: 'partials/boards.html',
        controller: 'BoardsController'
      }).when('/lists', {
        templateUrl: 'partials/lists.html',
        controller: 'ListsController'
      }).otherwise({
        redirectTo: '/login'
      });
    }
  ]).factory('TrelloService', [
    '$http', '$cookieStore', function($http, $cookieStore) {
      var TrelloService;
      return TrelloService = (function() {
        var APIENDPOINT;

        function TrelloService() {}

        APIENDPOINT = "https://api.trello.com/1/";

        TrelloService.authorized = function() {
          return !!this.token();
        };

        TrelloService.token = function() {
          return $cookieStore.get("trelloToken");
        };

        TrelloService.setToken = function() {
          return $cookieStore.put("trelloToken", Trello.token());
        };

        TrelloService.user = function() {
          return $cookieStore.get("trelloUser");
        };

        TrelloService.setUser = function(username) {
          return $cookieStore.put('trelloUser', username);
        };

        TrelloService.boards = function() {
          return $http.get(APIENDPOINT + ("members/" + (this.user()) + "/boards?key=9115435cc98b67a65c3a6dcff606cb09&token=" + (this.token()) + "&filter=open"));
        };

        TrelloService.lists = function(boardId) {
          return $http.get(APIENDPOINT + ("boards/" + boardId + "/lists?key=9115435cc98b67a65c3a6dcff606cb09&token=" + (this.token())));
        };

        TrelloService.cards = function(listId) {
          return $http.get(APIENDPOINT + ("lists/" + listId + "/cards?key=9115435cc98b67a65c3a6dcff606cb09&token=" + (this.token()) + "&filter=open"));
        };

        return TrelloService;

      })();
    }
  ]).controller('MainController', [
    '$scope', '$http', '$location', '$rootScope', 'TrelloService', function($scope, $http, $location, $rootScope, TrelloService) {
      $scope.username = null;
      $scope.TrelloService = TrelloService;
      $scope.$watch(TrelloService.authorized, function(value) {
        if (value) {
          return $location.path(okUrl || 'login');
        }
      });
      $scope.login = function(okUrl) {
        TrelloService.setUser($scope.username);
        return Trello.authorize({
          type: "popup",
          success: function() {
            TrelloService.setToken();
            return $location.path(okUrl || "/boards");
          }
        });
      };
      $scope.logout = function(okUrl) {
        Trello.deauthorize();
        TrelloService.setToken();
        TrelloService.setUser(null);
        return $location.path(okUrl || 'login');
      };
      $scope.authorized = function() {
        return TrelloService.authorized();
      };
      if ($scope.authorized()) {
        return $location.path('/boards');
      }
    }
  ]).controller('BoardsController', [
    '$scope', '$location', '$http', '$rootScope', 'TrelloService', function($scope, $location, $http, $rootScope, TrelloService) {
      $scope.boards = [];
      $scope.index = function() {
        return TrelloService.boards().then(function(response) {
          return $scope.boards = response.data;
        });
      };
      $scope.lists = function(id) {
        return $location.path('lists').search({
          boardId: id
        });
      };
      return $scope.index();
    }
  ]).controller('ListsController', [
    '$scope', '$location', '$http', '$rootScope', 'TrelloService', function($scope, $location, $http, $rootScope, TrelloService) {
      $scope.board = null;
      $scope.selectedListId = null;
      $scope.cards = null;
      $scope.drawPaper = function() {
        var card, content, i, len, project, projectKeyTitle, projects, ref, results;
        projects = {};
        ref = $scope.cards;
        for (i = 0, len = ref.length; i < len; i++) {
          card = ref[i];
          if (!card.name.match(/\{(.*)}/)) {
            break;
          }
          projectKeyTitle = card.name.match(/\{(.*)}/)[1];
          if (!projects[projectKeyTitle]) {
            projects[projectKeyTitle] = [];
          }
          projects[projectKeyTitle].push(card);
        }
        $("#paper").empty();
        results = [];
        for (project in projects) {
          $("<h2 />", {
            text: project
          }).appendTo("#paper");
          results.push((function() {
            var j, len1, ref1, results1;
            ref1 = projects[project];
            results1 = [];
            for (j = 0, len1 = ref1.length; j < len1; j++) {
              card = ref1[j];
              content = card.name;
              results1.push($("<div/>", {
                text: content
              }).appendTo("#paper"));
            }
            return results1;
          })());
        }
        return results;
      };
      $scope.drawSimplePaper = function() {
        var card, content, i, len, ref, results;
        $("#paper").empty();
        ref = $scope.cards;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          card = ref[i];
          content = card.name;
          results.push($("<div>", {
            text: content
          }).appendTo("#paper"));
        }
        return results;
      };
      $scope.index = function() {
        return TrelloService.lists($location.search().boardId).then(function(response) {
          $scope.lists = response.data;
          $scope.selectedListId || ($scope.selectedListId = $scope.lists[0].id);
          return $scope.show($scope.selectedListId);
        });
      };
      $scope.show = function(id) {
        $scope.selectedListId = id;
        return TrelloService.cards(id).then(function(response) {
          $scope.cards = response.data;
          return $scope.drawSimplePaper();
        });
      };
      return $scope.index();
    }
  ]);

}).call(this);
